### ISSUE TITLE
MapEntry broken on ClojureScript 1.10.238

### ISSUE THREAD

**Issue by Deraen** [frankiesardo/linked#6]
In new ClojureScript, `key` and `val` functions only work on proper `MapEntry` objects, but `linked` creates `vector` for map-entries:

https://github.com/frankiesardo/linked/blob/master/src/linked/map.cljc#L259

https://clojurescript.org/news/2018-03-26-release#_map_entries

This breaks e.g. `(key (first (linked/map ...)))`.

**Comment by frankiesardo** [comment]
Hi @Deraen thanks for reporting this.

I will push an updated version of linked that fixes this. Do you suggest it's best to push a `linked v1.3.0` that drops supports for older ClojureScript versions? I'm not sure how this change can be backwards-compatible.

**Comment by Deraen** [comment]
MapEntry type is available since 1.9.542.

Correct fix is to call `(MapEntry. k v nil)`.

Are you already working on this? I can have PR ready in a moment. The fix itself is simple, but looks like this project could use updated Boot/Boot tools etc.

**Comment by frankiesardo** [comment]
Yeah I was about to work on a fix but got stopped by old boot version. If you'd like to submit a PR I'm happy to merge it in.
