### ISSUE TITLE
Can't serialize LinkedMap with Jackson Databind

### ISSUE THREAD

**Issue by ikitommi** [frankiesardo/linked#8]
`isEmpty()` is not implemented:

```java
java.lang.AbstractMethodError: Method linked/map/LinkedMap.isEmpty()Z is abstract
  linked.map.LinkedMap.isEmpty(map.cljc)
  com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:627)
  com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:33)
  com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFields(MapSerializer.java:718)
  com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:639)
  com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:33)
  com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
  com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
  com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3893)
  com.fasterxml.jackson.databind.ObjectMapper.writeValueAsBytes(ObjectMapper.java:3231)
  jsonista.core$write_value_as_bytes.invokeStatic(core.clj:227)
  jsonista.core$write_value_as_bytes.invoke(core.clj:219)
```

**Comment by ikitommi** [comment]
also, `.entrySet()` is needed.

**Comment by alexandergunnarson** [comment]
Related are serialization issues with Transit, in which `.keySet()` is needed.

**Comment by ikitommi** [comment]
Porting all our libs to use Jsonista, and tests with linked are currently failing. Would it be possible to cut a release with tye fix?

**Comment by frankiesardo** [comment]
I've added a deps.edn to the repo if you can use that

**Comment by ikitommi** [comment]
The projects are still on Leiningen and about to release new versions that depend on this. Would it be possible to cut a release?

**Comment by frankiesardo** [comment]
Sure I can, but the app is broken on the boot infrastructure and I have no idea why https://circleci.com/gh/frankiesardo/linked/63 If you can help me fix this I have an automated job that pushes it to clojars

**Comment by ikitommi** [comment]
not a boot fan and no idea why it fails. but could it be pushed manually? Off to vacation today, would like to flush all things out before that

**Comment by ro6** [comment]
@frankiesardo Any more progress on a release incorporating https://github.com/ikitommi/linked/commit/ea58ccfcac5946195d4ef0e2ffe40b6d39387abe? I'm depending on the @ikitommi fork (`[ikitommi/linked "1.3.1-alpha1"]`) for now, but would love to get back on the main line.

**Comment by martinffx** [comment]
@ikitommi was this fixed in Jsonista, I'm still getting this error when setting up a swagger in compojure api?

**Comment by ikitommi** [comment]
What was the fix in jsonista? Can't recall..

**Comment by martinffx** [comment]
I excluded this lib and pulled in your copy of the jar with the fix in it.
